### ISSUE TITLE
JSON decoding error on cdp2descv2.py

### ISSUE THREAD

**Issue by ghost** [datacenter/who-moved-my-cli#11]
JSON is having issues parsing the output of 'show cdp neighbor'. Had to replace `cli.clid()` with `cli()` since it doesn't seem to be supported within NXOS within VIRL.

`nx-osv-1# >>> cdp = json.loads(cli('show cdp neighbor'))[`
`nx-osv-1# ...     'TABLE_cdp_neighbor_brief_info']['ROW_cdp_neighbor_brief_info']`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`File "/isan/python/scripts/json/__init__.py", line 326, in loads`
`return _default_decoder.decode(s)`
`File "/isan/python/scripts/json/decoder.py", line 366, in decode`
`obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
`File "/isan/python/scripts/json/decoder.py", line 384, in raw_decode`
`raise ValueError("No JSON object could be decoded")`
`ValueError: No JSON object could be decoded`

**Comment by ghost** [comment]
here's the CDP output without parsing through JSON:

`nx-osv-1# >>> cdp`
`'Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge\n`
`S - Switch, H - Host, I - IGMP, r - Repeater,\n                  V - V`
`oIP-Phone, D - Remotely-Managed-Device,\n                  s - Supports-STP-Dispu`
`te\n\nDevice-ID          Local Intrfce  Hldtme Capability  Platform      Port ID\`
`niosvl2-1.virl.com   mgmt0          134    R S I                   Gig0/0`
`\niosvl2-1.virl.com   Eth2/1         160    R S I                   Gig0/1`
`\n\nTotal entries displayed: 2\n'`  
`nx-osv-1# >>>`
